/** Saved English files only; no browser speech fallback. */
export const DIARY_WRITING_ASSET = 'audio.diary.pencil';
export const DIARY_FRAGMENT_AUDIO: Readonly<Record<string, { assetId: string; english: string; voiceProfileId: string }>> = {
  'first-i': { assetId: 'voice.diary.first-i', english: 'I', voiceProfileId: 'voice.charlie.en' },
  'first-mouse': { assetId: 'voice.diary.first-mouse', english: 'the little mouse', voiceProfileId: 'voice.charlie.en' },
  'first-try': { assetId: 'voice.diary.first-try', english: 'still want to', voiceProfileId: 'voice.charlie.en' },
  'first-again': { assetId: 'voice.diary.first-again', english: 'try again', voiceProfileId: 'voice.charlie.en' },
  'first-test': { assetId: 'voice.diary.first-test', english: 'do well on the test', voiceProfileId: 'voice.charlie.en' },
  'first-route': { assetId: 'voice.diary.first-route', english: 'run fast', voiceProfileId: 'voice.charlie.en' },
  'first-smart': { assetId: 'voice.diary.first-smart', english: 'get smarter', voiceProfileId: 'voice.charlie.en' },
  'first-remember': { assetId: 'voice.diary.first-remember', english: 'remember today', voiceProfileId: 'voice.charlie.en' },
  'first-today': { assetId: 'voice.diary.first-today', english: 'today', voiceProfileId: 'voice.charlie.en' },
  'preop-i': { assetId: 'voice.diary.preop-i', english: 'I', voiceProfileId: 'voice.charlie.en' },
  'preop-want': { assetId: 'voice.diary.preop-want', english: 'still want to', voiceProfileId: 'voice.charlie.en' },
  'preop-bread': { assetId: 'voice.diary.preop-bread', english: 'bag the bread', voiceProfileId: 'voice.charlie.en' },
  'preop-word': { assetId: 'voice.diary.preop-word', english: 'know that word', voiceProfileId: 'voice.charlie.en' },
  'preop-again': { assetId: 'voice.diary.preop-again', english: 'read it again', voiceProfileId: 'voice.charlie.en' },
  'preop-remember': { assetId: 'voice.diary.preop-remember', english: 'remember today', voiceProfileId: 'voice.charlie.en' },
  'preop-ask': { assetId: 'voice.diary.preop-ask', english: 'ask about the operation', voiceProfileId: 'voice.charlie.en' },
  'preop-scared': { assetId: 'voice.diary.preop-scared', english: 'a little scared', voiceProfileId: 'voice.charlie.en' },
  'preop-slow': { assetId: 'voice.diary.preop-slow', english: 'take my time', voiceProfileId: 'voice.charlie.en' },
  'recovery-i': { assetId: 'voice.diary.recovery-i', english: 'I', voiceProfileId: 'voice.charlie.en' },
  'recovery-want': { assetId: 'voice.diary.recovery-want', english: 'still want to', voiceProfileId: 'voice.charlie.en' },
  'recovery-rest': { assetId: 'voice.diary.recovery-rest', english: 'rest a while', voiceProfileId: 'voice.charlie.en' },
  'recovery-paper': { assetId: 'voice.diary.recovery-paper', english: 'keep this paper', voiceProfileId: 'voice.charlie.en' },
  'recovery-look': { assetId: 'voice.diary.recovery-look', english: 'look again', voiceProfileId: 'voice.charlie.en' },
  'recovery-ask': { assetId: 'voice.diary.recovery-ask', english: 'ask someone to read with me', voiceProfileId: 'voice.charlie.en' },
  'recovery-remember': { assetId: 'voice.diary.recovery-remember', english: 'remember that word', voiceProfileId: 'voice.charlie.en' },
  'recovery-near': { assetId: 'voice.diary.recovery-near', english: 'keep it a little closer', voiceProfileId: 'voice.charlie.en' },
  'recovery-later': { assetId: 'voice.diary.recovery-later', english: 'it is all right to wait', voiceProfileId: 'voice.charlie.en' },
  'ascending-i': { assetId: 'voice.diary.ascending-i', english: 'I', voiceProfileId: 'voice.charlie.en' },
  'ascending-now': { assetId: 'voice.diary.ascending-now', english: 'now', voiceProfileId: 'voice.charlie.en' },
  'ascending-begin': { assetId: 'voice.diary.ascending-begin', english: 'am starting to understand', voiceProfileId: 'voice.charlie.en' },
  'ascending-want': { assetId: 'voice.diary.ascending-want', english: 'want to work out', voiceProfileId: 'voice.charlie.en' },
  'ascending-lever': { assetId: 'voice.diary.ascending-lever', english: 'how the lever turns the gear', voiceProfileId: 'voice.charlie.en' },
  'ascending-roller': { assetId: 'voice.diary.ascending-roller', english: 'why the rollers move together', voiceProfileId: 'voice.charlie.en' },
  'ascending-links': { assetId: 'voice.diary.ascending-links', english: 'how these parts fit together', voiceProfileId: 'voice.charlie.en' },
  'ascending-try': { assetId: 'voice.diary.ascending-try', english: 'then try it myself', voiceProfileId: 'voice.charlie.en' },
  'ascending-happy': { assetId: 'voice.diary.ascending-happy', english: 'feeling a little pleased', voiceProfileId: 'voice.charlie.en' },
  'ascending-pace': { assetId: 'voice.diary.ascending-pace', english: 'one step at a time', voiceProfileId: 'voice.charlie.en' },
  'peak-i': { assetId: 'voice.diary.peak-i', english: 'I', voiceProfileId: 'voice.charlie.en' },
  'peak-understanding': { assetId: 'voice.diary.peak-understanding', english: 'the pleasure of understanding something', voiceProfileId: 'voice.charlie.en' },
  'peak-pages': { assetId: 'voice.diary.peak-pages', english: 'records that once seemed separate', voiceProfileId: 'voice.charlie.en' },
  'peak-question': { assetId: 'voice.diary.peak-question', english: 'makes me want to keep asking', voiceProfileId: 'voice.charlie.en' },
  'peak-explore': { assetId: 'voice.diary.peak-explore', english: 'want to follow these connections', voiceProfileId: 'voice.charlie.en' },
  'peak-follow': { assetId: 'voice.diary.peak-follow', english: 'can already', voiceProfileId: 'voice.charlie.en' },
  'peak-before': { assetId: 'voice.diary.peak-before', english: 'before the professor finishes', voiceProfileId: 'voice.charlie.en' },
  'peak-experiment': { assetId: 'voice.diary.peak-experiment', english: 'think of the next experiment', voiceProfileId: 'voice.charlie.en' },
  'peak-cue': { assetId: 'voice.diary.peak-cue', english: 'how a cue helps us remember', voiceProfileId: 'voice.charlie.en' },
  'peak-bakery': { assetId: 'voice.diary.peak-bakery', english: 'follow the lever to the gear', voiceProfileId: 'voice.charlie.en' },
  'peak-test': { assetId: 'voice.diary.peak-test', english: 'recognize wings in the ink', voiceProfileId: 'voice.charlie.en' },
  'peak-maze': { assetId: 'voice.diary.peak-maze', english: 'connect a turn in the maze with a cue', voiceProfileId: 'voice.charlie.en' },
  'peak-connect': { assetId: 'voice.diary.peak-connect', english: 'connect with each other on one page', voiceProfileId: 'voice.charlie.en' },
  'peak-joy': { assetId: 'voice.diary.peak-joy', english: 'with the joy of finding something new', voiceProfileId: 'voice.charlie.en' },
  'peak-more': { assetId: 'voice.diary.peak-more', english: 'think one step further', voiceProfileId: 'voice.charlie.en' },
  'last-i': { assetId: 'voice.diary.last-i', english: 'I', voiceProfileId: 'voice.charlie.en' },
  'last-before': { assetId: 'voice.diary.last-before', english: 'the person I was', voiceProfileId: 'voice.charlie.en' },
  'last-want': { assetId: 'voice.diary.last-want', english: 'still want to remember', voiceProfileId: 'voice.charlie.en' },
  'last-keep': { assetId: 'voice.diary.last-keep', english: 'do not want to forget', voiceProfileId: 'voice.charlie.en' },
  'last-know': { assetId: 'voice.diary.last-know', english: 'understood', voiceProfileId: 'voice.charlie.en' },
  'last-people': { assetId: 'voice.diary.last-people', english: 'the people who were kind to me', voiceProfileId: 'voice.charlie.en' },
  'last-mouse': { assetId: 'voice.diary.last-mouse', english: 'Algernon', voiceProfileId: 'voice.charlie.en' },
  'last-word': { assetId: 'voice.diary.last-word', english: 'that word... the one I cannot find', voiceProfileId: 'voice.charlie.en' },
  'last-happiness': { assetId: 'voice.diary.last-happiness', english: 'the joy of understanding that lesson', voiceProfileId: 'voice.charlie.en' },
  'last-stay': { assetId: 'voice.diary.last-stay', english: 'leave it on this page for now', voiceProfileId: 'voice.charlie.en' },
};
export function diaryVoiceForFragment(fragmentId: string) {
  return DIARY_FRAGMENT_AUDIO[fragmentId];
}
