import { useEffect, useRef, useState } from 'react';
import { LaboratoryStage, BakeryStage } from './components/world';
import { IllustratedNPC } from './components/interaction';
import { SubtitleBlock, ReportEditor } from './components/narrative/SubtitleBlock';
import { CognitionGraph } from './cognition/CognitionGraph';
import { MazeBox } from './cognition/MazeBox';
import { BAKERY_GRAPH } from './cognition/presets';
import { observations, testGraph, machineGraph, lines } from './content/experience';
import type { CognitionState } from './core/types';
import type { ReportDraft } from './narrative/report';
import { AudioManager } from './audio/AudioManager';
import { resolveAudioAsset } from './core/audio-registry';
import { VOICE_PROFILES_EXAMPLE } from './audio/voice-profiles.example';
import { PERCEPTION_PRESETS } from './audio/perception';
import './app.css';
type Step='title'|'lab'|'test'|'diary'|'bakery'|'gain'|'machine'|'revisit'|'peak-report'|'decline'|'last-report'|'finish';
type Pair={en:string;zhHans:string};
export default function App(){
 const [step,setStep]=useState<Step>('title'),[text,setText]=useState<Pair>(lines.welcome),[speaker,setSpeaker]=useState('Dr. Strauss');
 const [observed,setObserved]=useState<string[]>([]),[edges,setEdges]=useState<string[]>([]),[bread,setBread]=useState(0),[choice,setChoice]=useState(''),[report,setReport]=useState<ReportDraft|null>(null),[intent,setIntent]=useState('');
 const [transition,setTransition]=useState(false),[muted,setMuted]=useState(false),[voicePreview,setVoicePreview]=useState(false),[audioNote,setAudioNote]=useState(''),[speaking,setSpeaking]=useState(false);
 const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined), speechTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),audio=useRef<AudioManager|null>(null);
 const phase:CognitionState['phase']=['decline','last-report'].includes(step)?'DECLINE':['machine','revisit','peak-report'].includes(step)?'PEAK':step==='gain'?'ASCENDING':'LOW';
 const cognition:CognitionState={phase,affordances:[],perceivedDetail:phase==='PEAK'?1:phase==='DECLINE'?.3:.4};
 const bakery=['bakery','gain','machine','revisit','peak-report','decline','last-report'].includes(step);
 useEffect(()=>()=>{clearTimeout(timer.current);clearTimeout(speechTimer.current);void audio.current?.dispose();},[]);
 useEffect(()=>{audio.current?.setPerception(phase==='PEAK'?PERCEPTION_PRESETS.clear:phase==='DECLINE'?PERCEPTION_PRESETS.strained:PERCEPTION_PRESETS.softened);},[phase]);
 const say=(line:Pair,person='Charlie')=>{setText(line);setSpeaker(person);setSpeaking(true);clearTimeout(speechTimer.current);speechTimer.current=setTimeout(()=>setSpeaking(false),Math.min(6000,line.en.length*45));if(voicePreview){const profile=VOICE_PROFILES_EXAMPLE.find(v=>v.characterId===(person==='Charlie'?'charlie':'dr-strauss'))!;const result=audio.current?.previewVoice(line.en,profile);if(result&&!result.available)setAudioNote('English voice unavailable on this browser. / 当前浏览器没有英语声线。');}};
 const go=(next:Step,line?:Pair)=>{audio.current?.stopVoice();setSpeaking(false);setEdges([]);setReport(null);setStep(next);if(line)say(line);};
 const bridge=(next:Step,line:Pair)=>{setTransition(true);void audio.current?.playSound('audio.paper.prototype').catch(()=>{});timer.current=setTimeout(()=>{go(next,line);setTransition(false);},1400);};
 const begin=()=>{if(!audio.current)audio.current=new AudioManager(resolveAudioAsset);void audio.current.unlock().then(()=>audio.current!.playSound('audio.room-tone.prototype',true)).catch(()=>setAudioNote('Audio unavailable. / 音频暂不可用。'));go('lab',lines.welcome);setSpeaker('Dr. Strauss');};
 const connect=(id:string)=>{setEdges(previous=>previous.includes(id)?previous:[...previous,id]);void audio.current?.playSound('audio.chime.prototype').catch(()=>{});};
 const Stage=bakery?BakeryStage:LaboratoryStage;
 return <main className={`game game--${phase.toLowerCase()}`}>
  <div className="world"><Stage><IllustratedNPC name={bakery?'Gimpy':'Dr. Strauss'} role={bakery?'baker':'researcher'} mood={bakery?(step==='revisit'?'uneasy':'neutral'):'warm'} speaking={speaking&&speaker!=='Charlie'} onInteract={()=>say(bakery?(bread<3?lines.bakery:lines.success):lines.welcome,bakery?'Gimpy':'Dr. Strauss')}/></Stage></div>
  <header className="game-header"><a href="#" onClick={e=>{e.preventDefault();setStep('title');audio.current?.stopVoice();}}>ALGERNON<span>A STUDY IN REMEMBERING</span></a><nav><button onClick={()=>{setVoicePreview(v=>!v);if(voicePreview)audio.current?.stopVoice();}}>Voice preview {voicePreview?'on':'off'}</button><button onClick={()=>{setMuted(v=>!v);audio.current?.setMuted(!muted);}}>{muted?'Unmute':'Sound on'}</button><a href="/project-status.html" target="_blank" rel="noreferrer">Studio ↗</a></nav></header>
  {step==='title'?<section className="title-page"><p className="kicker">AN INTERACTIVE NARRATIVE</p><h1>Flowers<br/>for <em>Algernon.</em></h1><div className="fine-line"/><p className="title-quote">The world hasn't changed.<br/>The way you see it will.</p><button className="primary" onClick={begin}>Open your eyes <span>睁开眼睛 →</span></button><p className="build-note">First playable study · 插画与声音为开发原型<br/>English voice preview · EN / 简中</p></section>:<>
  <div className="chapter-mark"><span>{bakery?'D O N N E R ’ S   B A K E R Y':'B E E K M A N   L A B O R A T O R Y'}</span><i>{bakery?'Bread, flour, familiar faces.':'Paper. A clock. Someone waiting.'}</i></div>
  {step==='lab'&&<><div className="hotspots">{Object.entries(observations).map(([key,line],i)=><button key={key} className={`hotspot hotspot--${i}`} onClick={()=>{setObserved(a=>a.includes(key)?a:[...a,key]);say(line);}}><b>＋</b><span>{key==='book'?'Look at the book':key==='paper'?'Look at the paper':'Watch Algernon'}</span></button>)}</div><div className="action-tray"><small>Look around. / 先看看周围。</small><button className="primary" disabled={observed.length<2} onClick={()=>go('test',lines.test)}>I'm ready <span>我准备好了 →</span></button></div></>}
  {step==='test'&&<section className="interaction-panel"><p className="kicker">A LITTLE INK ON PAPER</p><h2>What do you see?</h2><div className="inkblot" aria-label="An original symmetrical inkblot">❦</div><CognitionGraph model={testGraph} cognition={cognition} connectedEdgeIds={edges} onConnect={connect}/><button className="primary" disabled={!edges.length} onClick={()=>go('diary',{en:'Maybe I did all right. I should write it down.',zhHans:'也许我做得还不错。我应该写下来。'})}>A butterfly, maybe. <span>也许是蝴蝶 →</span></button></section>}
  {['diary','peak-report','last-report'].includes(step)&&<section className="interaction-panel report-panel"><p className="kicker">PROGRESS REPORT · {step==='diary'?'01':step==='peak-report'?'07':'11'}</p><h2>{step==='last-report'?'I remember knowing.':'A page of my own.'}</h2><ReportEditor key={step} phase={phase} initialText={step==='last-report'?intent:''} onSaveReport={r=>{setReport(r);if(step==='peak-report')setIntent(r.rawText);}}/>{report&&<button className="primary" onClick={()=>step==='diary'?bridge('bakery',lines.bakery):step==='peak-report'?bridge('decline',lines.decline):go('finish')}>Close the notebook <span>合上笔记本 →</span></button>}</section>}
  {step==='bakery'&&<section className="interaction-panel compact"><p className="kicker">THE MORNING SHIFT</p><h2>Something I know.</h2><p>Three loaves. One paper bag.<br/><small>三条面包。一个纸袋。</small></p><button className="bread-action" disabled={bread>=3} onClick={()=>{setBread(b=>b+1);say(bread===2?lines.laughter:lines.bakery);}}>♧ <span>{bread<3?'Bag a loaf / 装一条面包':'The bag is ready / 装好了'}</span><b>{bread} / 3</b></button>{bread===3&&<button className="primary" onClick={()=>bridge('gain',lines.gain)}>Another morning <span>又一个清晨 →</span></button>}</section>}
  {step==='gain'&&<section className="interaction-panel compact"><p className="kicker">THE SAME MACHINE</p><h2>Wait. I see it.</h2><p>The lever. The turning wheel.<br/>They aren't separate things.</p><p lang="zh-Hans">拉杆。转动的轮子。它们不是独立的。</p><button className="primary" onClick={()=>go('machine',lines.gain)}>Look closer <span>仔细看看 →</span></button></section>}
  {['machine','decline'].includes(step)&&<section className="interaction-panel"><p className="kicker">THE DOUGH ROLLER</p><h2>{step==='decline'?'There was a connection.':'One thing moves another.'}</h2><CognitionGraph key={step} model={machineGraph} cognition={cognition} connectedEdgeIds={edges} onConnect={connect}/>{step==='machine'?<button className="primary" disabled={edges.length<3} onClick={()=>go('revisit',lines.success)}>Turn the machine <span>开动机器 →</span></button>:<><p className="remembered">lever — gear — roller — dough</p><p>I used to understand this. / 我以前懂得这个。</p><button className="primary" onClick={()=>go('last-report',lines.decline)}>Find my notebook <span>找我的笔记本 →</span></button></>}</section>}
  {step==='revisit'&&<section className="interaction-panel"><p className="kicker">THE SAME LAUGHTER</p><h2>It was always there.</h2><CognitionGraph model={BAKERY_GRAPH} cognition={cognition} connectedEdgeIds={edges} onConnect={connect}/>{edges.length>0&&<div className="choices">{['I only did what I was asked.','Why are you angry?','Say nothing.'].map((line,i)=><button key={line} onClick={()=>{setChoice(line);say({en:i===0?'He looks away. Nobody asks how I did it.':i===1?'“Nobody is angry,” he says, without looking at me.':'I stay quiet. So does he.',zhHans:i===0?'他移开目光。没有人问我是怎样做到的。':i===1?'“没人生气，”他说，却不看我。':'我沉默。他也是。'});}}>{line}<small>{['我只是做了被要求的事。','你为什么生气？','保持沉默。'][i]}</small></button>)}</div>}{choice&&<button className="primary" onClick={()=>go('peak-report',lines.return)}>Write it down <span>记下来 →</span></button>}</section>}
  {step==='finish'&&<section className="interaction-panel compact"><p className="kicker">END OF THE FIRST STUDY</p><h2>You remember.</h2><p>That is where we begin.<br/><small>这是我们的起点。</small></p><p className="build-note">本次切片到此结束；课堂、研究、会议与完整结局仍在开发计划中。</p><button className="primary" onClick={()=>{setObserved([]);setBread(0);setChoice('');setIntent('');go('lab',lines.welcome);}}>Return to the room <span>回到房间 →</span></button></section>}
  {step!=='finish'&&<footer className="subtitles"><div className="speaker">{speaker}</div><SubtitleBlock text={text}/><button className="replay" aria-label="Replay English voice" onClick={()=>say(text,speaker)}>↺</button></footer>}
  <MazeBox cognition={cognition} suspended={step==='finish'}/>
  </>}
  {audioNote&&<div className="audio-note" role="status" onClick={()=>setAudioNote('')}>{audioNote}</div>}
  {transition&&<div className="ink-transition" aria-label="Turning the page"><span/><i/><span/></div>}
 </main>;
}
